name: slack CI

on:
  workflow_dispatch:
  schedule:
   - cron: "30 8 * * 1,5"  # UTC 기준, 매주 월요일과 금요일 오전 8시 30분 실행 (KST 오후 5시 30분)
  
jobs:
  post_announcement_message:
    runs-on: ubuntu-latest
    steps:
      - name: action code checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10
      
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: run main.py
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        run: python3 main.py
